### ISSUE TITLE
Gallery HTML code could be generated by iterating over gallery.json data

### ISSUE THREAD

**Issue by nhoizey** [tannerdolby/eleventy-photo-gallery#1]
Instead of a static HTML code in `_includes/layouts/base.njk`, you could iterate over data available in `_data/gallery.json`.

This JSON file should be an array instead of an object:

```json
[
    {
        "name": "imageOne",
        "src": "/images/shop-plants-small.jpg",
        "ng_large_src": "/images/shop-plants-large.webp 1024w",
        "ng_med_src": "/images/shop-plants-med.webp 640w",
        "ng_small_src": "/images/shop-plants-small.webp 320w",
        "large_src": "/images/shop-plants-large.jpg 1024w",
        "med_src": "/images/shop-plants-med.jpg 640w",
        "small_src": "/images/shop-plants-small.jpg 320w",
        "alt": "Terrace outside shop window with green plants and pink tree on night street"
    },
    {
…
```

Then, in `_includes/layouts/base.njk` you can loop:

```nunjucks
<section class="gallery">
  <div class="image-grid">
    {% for image in gallery %}
      <div class="image-container">
        … # Here, replace `gallery.imageOne` with `image`
      </div>
    {% endfor %}
  </div>
</section>
```

You probably need to add the image page URL to the data file also.

**Comment by tannerdolby** [comment]
I converted the object to an array and used a for loop to iterate through each image in `gallery.json` like you stated above. This allowed me to remove a bunch of gallery HTML from the `base.njk` layout. 

Everything works like a charm. Thank you! @nhoizey

**Comment by nhoizey** [comment]
You're welcome!
