### ISSUE TITLE
Image metadata could come from the gallery.json datafile too

### ISSUE THREAD

**Issue by nhoizey** [tannerdolby/eleventy-photo-gallery#2]
I see there are image metadata both in `_data/gallery.json` and each `gallery/image-one/index.md` Mardown file.

With #1, you could also move all metadata in `_data/gallery.json` and generate image pages without needing any Markdown file at all, using Eleventy's pagination/iteration feature: https://www.11ty.dev/docs/pages-from-data/

**Comment by tannerdolby** [comment]
I moved all the image metadata into `_data/gallery.json` and generated image pages with Eleventy's pagination/iteration feature! I'm glad to have gotten rid of those extra Markdown files. Thanks! @nhoizey

**Comment by nhoizey** [comment]
You're welcome!
