### ISSUE TITLE
Replace Speedlify-score HTML with social icons?

### ISSUE THREAD

**Issue by tannerdolby** [tannerdolby/eleventy-photo-gallery#8]
Although, [Speedlify](https://www.11ty.dev/speedlify/) is really nice to remind the user how performant a site is, I don't think *everyone* would want to have the performance metrics in the footer for just a personal art collection or photo gallery website (which this template is made for). 

Consuming the speedlify API cached data which is running from my own local [speedlify instance](https://tdspeedlify.netlify.app) does affect the performance slightly, so maybe thats my argument for interchanging it and the accompanying JS for the static API with social icons.

Adding a list of social links to the footer may be more desired than tabbing onto the speedlify component which is an external link.

If anyone wants to weigh in on this, that'd be cool. If not, I probably will replace the `speedlify-score` component with a `<ul>` of social icons as links to the site owners social accounts.

**Comment by nhoizey** [comment]
I fully agree! 👍

**Comment by tannerdolby** [comment]
Ok great. Thanks for the feedback! @nhoizey 

I will implement this later today or tomorrow.

**Comment by tannerdolby** [comment]
Replaced `speedlify-score` component with a unordered list of social links in commit [535d196](https://github.com/tannerdolby/eleventy-photo-gallery/commit/535d196b6c1d8660ad21db64b1a4583f09bd9369). Some other stuff was fixed with this commit but social links have now replaced the speedlify-score component in footer!
